export interface TrafficList {
  date: string;
  value: number;
  delta: {
    up: boolean;
    value: number;
  };
  comparison: {
    prevDate: string;
    prevValue: number;
    nextDate: string;
    nextValue: number;
  };
}


export const TRAFFIC_LIST_DUMMY_WEEKLY = [
  {
    "date":"Mon",
    "value":818,
    "delta":{
      "up":false,
      "value":2
    },
    "comparison":{
      "prevDate":"Sun",
      "prevValue":36,
      "nextDate":"Mon",
      "nextValue":34
    }
  },
  {
    "date":"Tue",
    "value":407,
    "delta":{
      "up":false,
      "value":14
    },
    "comparison":{
      "prevDate":"Mon",
      "prevValue":34,
      "nextDate":"Tue",
      "nextValue":20
    }
  },
  {
    "date":"Wed",
    "value":73,
    "delta":{
      "up":true,
      "value":72
    },
    "comparison":{
      "prevDate":"Tue",
      "prevValue":20,
      "nextDate":"Wed",
      "nextValue":92
    }
  },
  {
    "date":"Thu",
    "value":574,
    "delta":{
      "up":false,
      "value":64
    },
    "comparison":{
      "prevDate":"Wed",
      "prevValue":92,
      "nextDate":"Thu",
      "nextValue":28
    }
  },
  {
    "date":"Fri",
    "value":969,
    "delta":{
      "up":true,
      "value":19
    },
    "comparison":{
      "prevDate":"Thu",
      "prevValue":28,
      "nextDate":"Fri",
      "nextValue":47
    }
  },
  {
    "date":"Sat",
    "value":580,
    "delta":{
      "up":true,
      "value":53
    },
    "comparison":{
      "prevDate":"Fri",
      "prevValue":47,
      "nextDate":"Sat",
      "nextValue":100
    }
  },
  {
    "date":"Sun",
    "value":177,
    "delta":{
      "up":false,
      "value":92
    },
    "comparison":{
      "prevDate":"Sat",
      "prevValue":100,
      "nextDate":"Sun",
      "nextValue":8
    }
  }
];

export const TRAFFIC_LIST_DUMMY_MONTHLY = [
  {
    "date":"Jan",
    "value":829,
    "delta":{
      "up":false,
      "value":45
    },
    "comparison":{
      "prevDate":"Dec",
      "prevValue":48,
      "nextDate":"Jan",
      "nextValue":3
    }
  },
  {
    "date":"Feb",
    "value":524,
    "delta":{
      "up":true,
      "value":11
    },
    "comparison":{
      "prevDate":"Jan",
      "prevValue":3,
      "nextDate":"Feb",
      "nextValue":14
    }
  },
  {
    "date":"Mar",
    "value":948,
    "delta":{
      "up":false,
      "value":6
    },
    "comparison":{
      "prevDate":"Feb",
      "prevValue":14,
      "nextDate":"Mar",
      "nextValue":8
    }
  },
  {
    "date":"Apr",
    "value":711,
    "delta":{
      "up":true,
      "value":2
    },
    "comparison":{
      "prevDate":"Mar",
      "prevValue":8,
      "nextDate":"Apr",
      "nextValue":10
    }
  },
  {
    "date":"May",
    "value":421,
    "delta":{
      "up":true,
      "value":38
    },
    "comparison":{
      "prevDate":"Apr",
      "prevValue":10,
      "nextDate":"May",
      "nextValue":48
    }
  },
  {
    "date":"Jun",
    "value":579,
    "delta":{
      "up":true,
      "value":50
    },
    "comparison":{
      "prevDate":"May",
      "prevValue":48,
      "nextDate":"Jun",
      "nextValue":98
    }
  },
  {
    "date":"Jul",
    "value":662,
    "delta":{
      "up":false,
      "value":55
    },
    "comparison":{
      "prevDate":"Jun",
      "prevValue":98,
      "nextDate":"Jul",
      "nextValue":43
    }
  },
  {
    "date":"Aug",
    "value":737,
    "delta":{
      "up":true,
      "value":9
    },
    "comparison":{
      "prevDate":"Jul",
      "prevValue":43,
      "nextDate":"Aug",
      "nextValue":52
    }
  },
  {
    "date":"Sep",
    "value":939,
    "delta":{
      "up":true,
      "value":31
    },
    "comparison":{
      "prevDate":"Aug",
      "prevValue":52,
      "nextDate":"Sep",
      "nextValue":83
    }
  },
  {
    "date":"Oct",
    "value":585,
    "delta":{
      "up":false,
      "value":39
    },
    "comparison":{
      "prevDate":"Sep",
      "prevValue":83,
      "nextDate":"Oct",
      "nextValue":44
    }
  },
  {
    "date":"Nov",
    "value":72,
    "delta":{
      "up":true,
      "value":21
    },
    "comparison":{
      "prevDate":"Oct",
      "prevValue":44,
      "nextDate":"Nov",
      "nextValue":65
    }
  },
  {
    "date":"Dec",
    "value":952,
    "delta":{
      "up":true,
      "value":23
    },
    "comparison":{
      "prevDate":"Nov",
      "prevValue":65,
      "nextDate":"Dec",
      "nextValue":88
    }
  }
];

export const TRAFFIC_LIST_DUMMY_YEARLY = [
  {
    "date":"2010",
    "value":952,
    "delta":{
      "up":true,
      "value":61
    },
    "comparison":{
      "prevDate":"2009",
      "prevValue":27,
      "nextDate":"2010",
      "nextValue":88
    }
  },
  {
    "date":"2011",
    "value":969,
    "delta":{
      "up":false,
      "value":54
    },
    "comparison":{
      "prevDate":"2010",
      "prevValue":88,
      "nextDate":"2011",
      "nextValue":34
    }
  },
  {
    "date":"2012",
    "value":233,
    "delta":{
      "up":true,
      "value":51
    },
    "comparison":{
      "prevDate":"2011",
      "prevValue":34,
      "nextDate":"2012",
      "nextValue":85
    }
  },
  {
    "date":"2013",
    "value":922,
    "delta":{
      "up":true,
      "value":1
    },
    "comparison":{
      "prevDate":"2012",
      "prevValue":85,
      "nextDate":"2013",
      "nextValue":86
    }
  },
  {
    "date":"2014",
    "value":176,
    "delta":{
      "up":true,
      "value":7
    },
    "comparison":{
      "prevDate":"2013",
      "prevValue":86,
      "nextDate":"2014",
      "nextValue":93
    }
  },
  {
    "date":"2015",
    "value":852,
    "delta":{
      "up":false,
      "value":80
    },
    "comparison":{
      "prevDate":"2014",
      "prevValue":93,
      "nextDate":"2015",
      "nextValue":13
    }
  },
  {
    "date":"2016",
    "value":709,
    "delta":{
      "up":true,
      "value":56
    },
    "comparison":{
      "prevDate":"2015",
      "prevValue":13,
      "nextDate":"2016",
      "nextValue":69
    }
  },
  {
    "date":"2017",
    "value":526,
    "delta":{
      "up":false,
      "value":14
    },
    "comparison":{
      "prevDate":"2016",
      "prevValue":69,
      "nextDate":"2017",
      "nextValue":55
    }
  },
  {
    "date":"2018",
    "value":631,
    "delta":{
      "up":true,
      "value":5
    },
    "comparison":{
      "prevDate":"2017",
      "prevValue":55,
      "nextDate":"2018",
      "nextValue":60
    }
  }
];
