export const HISTORY_BALANCE_TYPES = {
  '-1': 'All',
  '0': 'New Bets',
  '1': 'Winning Bets',
  '2': 'Returned Bet',
  '3': 'Deposit',
  '4': 'Card Deposit',
  '5': 'Bonus',
  '6': 'Bonus Bet',
  '7': 'Commission',
  '8': 'Withdrawal',
  '9': 'Correction Up',
  '302': 'Correction Down',
  '10': 'Deposit by payment system',
  '12': 'Withdrawal request',
  '13': 'Authorized Withdrawal',
  '14': 'Withdrawal denied',
  '15': 'Withdrawal paid',
  '16': 'Pool Bet',
  '17': 'Pool Bet Win',
  '18': 'Pool Bet Return',
  '23': 'In the process of revision',
  '24': 'Removed for recalculation',
  '29': 'Free Bet Bonus received',
  '30': 'Wagering Bonus received',
  '31': 'Transfer from Gaming Wallet',
  '32': 'Transfer to Gaming Wallet',
  '37': 'Declined Superbet',
  '39': 'Bet on hold',
  '40': 'Bet cashout',
  '19': 'Fair',
  '20': 'Fair Win',
  '21': 'Fair Commission',
  '303': 'Bonus Correction'
}
